### ISSUE TITLE
(Suggestion) Move Data.Pool.Internal to a core package

### ISSUE THREAD

**Issue by jappeace** [scrive/pool#32]
Following the ideas from this [blogpost](http://nikita-volkov.github.io/internal-convention-is-a-mistake/).

Moving the Data.Pool.Internal module to a core or internal pacakge (eg data-pool-core), allows internal changes to be versioned as well.

**Comment by arybczak** [comment]
I don't agree with this blog post and will not be doing this.

**Comment by jappeace** [comment]
Perhaps you could give an elaboration?

**Comment by arybczak** [comment]
Ehh, so there is a never ending discussion how this should be handled (see this recent [thread on discourse](https://discourse.haskell.org/t/pvp-compliance-of-internal-modules/6784)).

I personally don't want to do this because it would give me one more package to maintain. Sounds small, but then you could argue "if you did it for this library, you should also do this for others" and suddenly I'm maintaining 10+ more packages.

The convention of `.Internal` packages not following PVP might be ad-hoc and strictly speaking breaks PVP, but it's a good balance between saving work for maintainers and not annoying advanced users that want to access internals of a library for some reason.

Also seems to work well in practice, so I don't see why I should make life harder for myself only because someone is annoyed by its imperfection.
